/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AcceptInvitationIdRouteImport } from './routes/accept-invitation/$id'
import { Route as Oauth2SplatRouteImport } from './routes/oauth2/$'
import { Route as AuthOrganizationsIndexRouteImport } from './routes/_auth/organizations/index'
import { Route as AuthOrganizationsSlugRouteImport } from './routes/_auth/organizations/$slug'
import { Route as AuthPackagesIndexRouteImport } from './routes/_auth/packages/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthPackagesHandleSlugRouteImport } from './routes/_auth/packages/$handle/$slug'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AcceptInvitationIdRoute = AcceptInvitationIdRouteImport.update({
  id: '/accept-invitation/$id',
  path: '/accept-invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2SplatRoute = Oauth2SplatRouteImport.update({
  id: '/oauth2/$',
  path: '/oauth2/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrganizationsIndexRoute = AuthOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOrganizationsSlugRoute = AuthOrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPackagesIndexRoute = AuthPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPackagesHandleSlugRoute = AuthPackagesHandleSlugRouteImport.update({
  id: '/packages/$handle/$slug',
  path: '/packages/$handle/$slug',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/oauth2/$': typeof Oauth2SplatRoute
  '/organizations/$slug': typeof AuthOrganizationsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/': typeof AuthOrganizationsIndexRoute
  '/packages/': typeof AuthPackagesIndexRoute
  '/packages/$handle/$slug': typeof AuthPackagesHandleSlugRoute
}
export interface FileRoutesByTo {
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/oauth2/$': typeof Oauth2SplatRoute
  '/': typeof AuthIndexRoute
  '/organizations/$slug': typeof AuthOrganizationsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations': typeof AuthOrganizationsIndexRoute
  '/packages': typeof AuthPackagesIndexRoute
  '/packages/$handle/$slug': typeof AuthPackagesHandleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/consent': typeof ConsentRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/accept-invitation/$id': typeof AcceptInvitationIdRoute
  '/oauth2/$': typeof Oauth2SplatRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/organizations/$slug': typeof AuthOrganizationsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/organizations/': typeof AuthOrganizationsIndexRoute
  '/_auth/packages/': typeof AuthPackagesIndexRoute
  '/_auth/packages/$handle/$slug': typeof AuthPackagesHandleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/device'
    | '/login'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/accept-invitation/$id'
    | '/oauth2/$'
    | '/organizations/$slug'
    | '/api/auth/$'
    | '/organizations/'
    | '/packages/'
    | '/packages/$handle/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/consent'
    | '/device'
    | '/login'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/accept-invitation/$id'
    | '/oauth2/$'
    | '/'
    | '/organizations/$slug'
    | '/api/auth/$'
    | '/organizations'
    | '/packages'
    | '/packages/$handle/$slug'
  id:
    | '__root__'
    | '/_auth'
    | '/consent'
    | '/device'
    | '/login'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/accept-invitation/$id'
    | '/oauth2/$'
    | '/_auth/'
    | '/_auth/organizations/$slug'
    | '/api/auth/$'
    | '/_auth/organizations/'
    | '/_auth/packages/'
    | '/_auth/packages/$handle/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  AcceptInvitationIdRoute: typeof AcceptInvitationIdRoute
  Oauth2SplatRoute: typeof Oauth2SplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/accept-invitation/$id': {
      id: '/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof AcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/$': {
      id: '/oauth2/$'
      path: '/oauth2/$'
      fullPath: '/oauth2/$'
      preLoaderRoute: typeof Oauth2SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/organizations/': {
      id: '/_auth/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthOrganizationsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/organizations/$slug': {
      id: '/_auth/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof AuthOrganizationsSlugRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/packages/': {
      id: '/_auth/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof AuthPackagesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/packages/$handle/$slug': {
      id: '/_auth/packages/$handle/$slug'
      path: '/packages/$handle/$slug'
      fullPath: '/packages/$handle/$slug'
      preLoaderRoute: typeof AuthPackagesHandleSlugRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthOrganizationsSlugRoute: typeof AuthOrganizationsSlugRoute
  AuthOrganizationsIndexRoute: typeof AuthOrganizationsIndexRoute
  AuthPackagesIndexRoute: typeof AuthPackagesIndexRoute
  AuthPackagesHandleSlugRoute: typeof AuthPackagesHandleSlugRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthOrganizationsSlugRoute: AuthOrganizationsSlugRoute,
  AuthOrganizationsIndexRoute: AuthOrganizationsIndexRoute,
  AuthPackagesIndexRoute: AuthPackagesIndexRoute,
  AuthPackagesHandleSlugRoute: AuthPackagesHandleSlugRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ConsentRoute: ConsentRoute,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  AcceptInvitationIdRoute: AcceptInvitationIdRoute,
  Oauth2SplatRoute: Oauth2SplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
