import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import * as esbuild from 'esbuild';

const packageRoot = path.join(import.meta.dirname, '..');
const distDir = path.join(packageRoot, 'dist');
const isolateOut = path.join(distDir, 'isolate.mjs');
const generatedPath = path.join(packageRoot, 'src/isolate-module.generated.ts');

await mkdir(distDir, { recursive: true });

await esbuild.build({
  bundle: true,
  entryPoints: [path.join(packageRoot, 'src/isolate/runtime.ts')],
  external: ['node:async_hooks'],
  format: 'esm',
  outfile: isolateOut,
  platform: 'neutral',
  target: 'es2022',
  write: true,
});

const isolateSource = await readFile(isolateOut, 'utf-8');
await writeFile(
  generatedPath,
  [
    '// Generated by scripts/build.ts. Do not edit.',
    `export const runtimeIsolateModuleSource = ${JSON.stringify(isolateSource)};`,
    '',
  ].join('\n')
);
